# Generated by Django 2.1.1 on 2018-09-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='policy',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='tags',
            field=models.CharField(choices=[('diversity', 'Diversity'), ('admissions', 'Admissions'), ('enrollment', 'Enrollment'), ('faculty', 'Faculty'), ('student affairs', 'Student Affairs'), ('administrative', 'Administrative'), ('fees', 'Fees'), ('data measures', 'Data Measures'), ('international students', 'International Students'), ('academic standards', 'Academic Standards'), ('athletics', 'Athletics'), ('title ix', 'Title IX'), ('accreditation', 'Accreditation')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
