# Generated by Django 2.1.1 on 2018-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180930_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='author',
            field=models.TextField(blank=True),
        ),
    ]
