# Generated by Django 2.1.1 on 2018-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180930_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='state',
            field=models.TextField(blank=True),
        ),
    ]
