# Generated by Django 2.1.1 on 2018-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180930_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='school',
            field=models.CharField(max_length=255),
        ),
    ]
